### ISSUE TITLE
Implement `Serial` trait

### ISSUE THREAD

**Issue by leo60228** [Rahix/atmega32u4-hal#2]
This shouldn't be very hard, but I don't have a working compiler right now.

**Comment by Rahix** [comment]
Hi @leo60228!

Yes, definitely possible.  Issue is, right now I am rethinking the whole design of the avr hal crates which is the reason I am not implementing new features.  If you need it before that rewrite happens I'll definitely accept a pull-request!

(One thing in particular is how to properly implement interrupt handling, which `Serial` kind of depends on)

**Comment by Rahix** [comment]
@leo60228: The new crates are now available and serial is already implemented!  Go over to [`avr-hal`](https://github.com/Rahix/avr-hal) for the new stuff.
